import Link from "next/link";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
        >
            <body className="min-h-full flex flex-col">
                <nav className="flex gap-12 h-15 justify-center items-center border-b-2 border-white">
                    <Link href={'/'} >Logo</Link>
                    <Link href={'/'} >Home</Link>
                    <Link href={'/blog'} >Blog</Link>
                </nav>
                {children}
            </body>
        </html>
    );
}
